security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                            admin:
                                password: '$2y$13$ZYWZK8hlmtkt909bKaKqre8DNbH6BM2.uzX1RlQAZSfdBENNVMaKC'
                                roles: ['ROLE_ADMIN']
                            usuario:
                                password: '$2y$13$ZYWZK8hlmtkt909bKaKqre8DNbH6BM2.uzX1RlQAZSfdBENNVMaKC'
                                roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: in_memory

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                default_target_path: dashboard
                enable_csrf: true

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
                path: /
                remember_me_parameter: _remember_me

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login,     roles: PUBLIC_ACCESS }
        - { path: ^/registro,  roles: PUBLIC_ACCESS }
        - { path: ^/verificar, roles: PUBLIC_ACCESS }
        - { path: ^/,          roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10